# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "6969:6969"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=6969
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      
      ## Keep configs, scrapers, and plugins here.
      - /home/patrick/docker/stashapp/config:/root/.stash
      ## Point this at your collection.
      - /media/adult:/data
      ## This is where your stash's metadata lives
      - /home/patrick/docker/stashapp/metadata:/metadata
      ## Any other cache content.
      - /home/patrick/docker/stashapp/cache:/cache
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /home/patrick/docker/stashapp/config/generated:/generated
